apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV3TVRreQpNVEEzTURWYUZ3MDBNakV3TVRreU1UQTNNRFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQnhtaHMyL2pGQkZMQk1kaFg3QlU2RGRzQUYxWVoyWmw2TmVkRFEreWwycVQzTVNEUwpWQTNvbXc1TDdVeGl1UFM1ZldETVV4WjBLSzY0NG4rT0d5dmE2R0xra282bWFaWUdmNnY3dVc5dW41UnRDN3k1CnVoKzB5VkJiYjR0RjIxRTFpZlFXZlA1TFg0RnA0L2w0VXhoa3NnN3hsUkpJNEhaMnZhRHYvQ3BqSG5JS2Y0dFUKZ25OYVFLMHJrQ1BiRE1BSFZtN3ordTZCbFc0bDNxaytraG5vK0tPOWQ0QXZ5V09hYmxhN0NidnNyaS80bEVLKwpWR2wyeFM5RFIxdmhtZjNqTXZQaHh2SnM1eW5neE9pTTNmWTBDZFREUXV1M25NaWtVR3k0NFFXUWdVLzBxMi9lCnlSWVBieFduNHc0Sm5yaHJUam5jNjAxUmxOQmdxcHlwUm51N0FnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNIaXpwdjFuU1kzMWJuamFYOQpMV0tHNUJRV1ZUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFlQmp0aHJ2Sk1OM21rNDNxU1JuTk94S1ZIc0lmCnoyNzJpZ0c2NmRjcExqSDhmYkkrem1RQWlDZ2s5bUh6M0owcDN5eCsvL0ZVYWs1SmpWM21oNEQwWVJINlBTYjYKaUhjOU4vbURLSlRtTk0zWFdLS0ZoWFhjZVpZL3ZGN2MzS3hSei9NQmI3MnFGenFpNWtwOFEyd3R4N2JoclFaWgp3alY4QzJ5N3VKc0R1WXBlNzBsbktOb21QT2RqYm1mUlh3MVY1YzFCNm0zR0FqU3c4NHRxQ0YrVWxwYW9rR0tiCk1BQ0swMHloN1pFTDBxZkZGempuQldsRkZCNkg1S1lyblIwelQ3alRPaUdJdXRaelpFMDBwZGhMMGNDK0s1UDQKREkxYzh1SWhZeTVBYU9uQTNCR2VtVFBxTWo3MTF1VjIyRlJzR0FyK25DYkRORUluczhpUHlFeXhMZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://b844370a-753c-42c4-9dce-72512ceb6c5c.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_2ae420bee22ad68958438019a5fde9efd19a6c5cb877053e4bc9815d80c11e3e
